apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: multi-k8s-mayoko-com-tls
spec:
  secretName: multi-k8s-mayoko-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: multi-k8s-mayoko.com
  dnsNames:
    - multi-k8s-mayoko.com
    - www.multi-k8s-mayoko.com